//
// Created by Skorppari on 08/03/2026.
//

#ifndef GREENHOUSE_PROJECT_SIMULATORTASK_H
#define GREENHOUSE_PROJECT_SIMULATORTASK_H


class SimulatorTask {
};


#endif //GREENHOUSE_PROJECT_SIMULATORTASK_H